### ISSUE TITLE
Investigate how to generate code from existing code

### ISSUE THREAD

**Issue by RaulBastian** [Serchland/Issues-Honeys#9]
GitHub model code generation

**Comment by RaulBastian** [comment]
Pasting here some notes for reference:

How to obtain a SyntaxTree:
--> SyntaxTree syntaxTree --> CSharpSyntaxTree.ParseText(text)

Get ClassDeclarationSyntax from a SyntaxTree 
--> SyntaxTree syntaxTree --> CSharpSyntaxTree.ParseText
--> syntaxTree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>().First();

MemberDeclarationSyntax:
--> member.ReplaceModifier(SyntaxKind.ProtectedKeyword, SyntaxKind.PublicKeyword);
--> member.ReplaceModifier(SyntaxKind.ProtectedKeyword, SyntaxKind.PublicKeyword);
--> member.RemoveModifier(SyntaxKind.VirtualKeyword);

**Comment by Serchland** [comment]
I hope it will reopen soon!
